# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83b1f4d3605dc64d139d58254987ca0997a06d5cfb5c83e3139398632cc511538c8818110be9c1e5d9805cd3153affe3727028ab6ae383a4d0c69ed237e29d9a

test:
  secret_key_base: 5a816053d0da9c32045cd8c218cf17583d8524eee1630086f9e2956f91528c7d98758b341995a6de2fb03870ac560e00325d15338c67c9eaa12b608c46c40535

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
